#!/bin/bash
reset
set -e
SERVER_URL=localhost:8000 wasm-pack build --target web
rollup ./main.js --format iife --file ./pkg/bundle.js
JWT_KEY=jkey DB_URL=mongodb://localhost:27017 cargo run --release --manifest-path=../connect4-server/Cargo.toml
