name: Connect 4 WASM

on:
  push:
    paths:
      - 'connect4/connect4-web/**'
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build WASM
      run: |
        rustup default nightly
        cd connect4
        cargo +nightly install wasm-pack
        wasm-pack build --target web
