name: Connect 4 WASM

on:
  push:
    paths:
      - 'connect4/connect4-web/**'
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build_WASM
      env:
        SERVER_URL: 'localhost:8000'
      run: |
        rustup default nightly
        cd connect4/connect4-web
        cargo +nightly install wasm-pack
        wasm-pack build --target web
    - name: Test
      env:
        SERVER_URL: 'localhost:8000'
      run: |
        cd connect4/connect4-web
        wasm-pack test --chrome --firefox
  # Lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v1
  #   - name: Lint
  #     run: |
  #       cd connect4/connect4-web
  #       rustup default nightly
  #       rustup component add rustfmt
  #       cargo +nightly fmt -- --check
  #   - name: Clippy
  #     run: |
  #       cd connect4/connect4-web
  #       rustup default nightly
  #       rustup component add clippy
  #       cargo +nightly clippy
