name: Connect 4 Lib

on:
  push:
    paths:
      - 'connect4/connect4-lib/**'

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build Lib
      run: |
        rustup default nightly
        cargo +nightly build --verbose --release --manifest-path=connect4/connect4-lib/Cargo.toml
    - name: Test
      run: cargo +nightly test --no-fail-fast --release --manifest-path=connect4/connect4-lib/Cargo.toml
  Lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Lint
      run: |
        rustup default nightly
        rustup component add rustfmt
        cargo +nightly fmt --check --manifest-path=connect4/connect4-lib/Cargo.toml
    - name: Clippy
      run: |
        rustup default nightly
        rustup component add clippy
        cargo +nightly clippy --manifest-path=connect4/connect4-lib/Cargo.toml
