name: Connect 4 Server

on:
  push:
    paths:
      - 'connect4/connect4-server/**'

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build Server
      run: cargo build --verbose --release --manifest-path=connect4/connect4-server/Cargo.toml
