name: Rust

on:
  push:
    paths:
      - 'connect4/connect4-lib/**'

jobs:
  Build Lib:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build Lib
      run: cargo build --verbose --release --manifest-path=connect4/connect4-lib/Cargo.toml

on:
  push:
    paths:
      - 'connect4/connect4-web'
jobs:
  Build WASM:
    runs-on: ubuntu-latest
        #- uses: actions/checkout@v2
        #- name: Build WASM
    steps:
    - uses: actions/checkout@v1
    - name: Build WASM
      run: |
        cd connect4
        cargo install wasm-pack
        wasm-pack build --target web
#    - name: Build
#      run: cargo build --verbose --manifest-path=connect4/Cargo.toml
#    - name: Run tests
#      run: cargo test --verbose --manifest-path=connect4/Cargo.toml
#
on:
  push:
    paths:
      - 'connect4/connect4-server'

jobs:
  Build Server:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build Server
      run: cargo build --verbose --release --manifest-path=connect4/connect4-server/Cargo.toml
