name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build WASM
      run: |
        cd connect4
        cargo install wasm-pack
        npm i -g rollup
        ./web
#    - name: Build
#      run: cargo build --verbose --manifest-path=connect4/Cargo.toml
#    - name: Run tests
#      run: cargo test --verbose --manifest-path=connect4/Cargo.toml
