name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose --manifest-path=rust_black_tree/Cargo.toml
    - name: Run tests
      run: cargo test --verbose --manifest-path=rust_black_tree/Cargo.toml
